import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp";
import type { Config } from "../../../../config.js";
import { registerGetUserPowerShell } from "./register-get-user.js";
import { registerNewUserPowerShell } from "./register-new-user.js";
import { registerRemoveUserPowerShell } from "./register-remove-user.js";
import { registerDisableUserPowerShell } from "./register-disable-user.js";
import { registerEnableUserPowerShell } from "./register-enable-user.js";
import { registerUnlockUserPowerShell } from "./register-unlock-user.js";
import { registerSetUserPowerShell } from "./register-set-user.js";
import { registerGetDomainPowerShell } from "./register-get-domain.js";
import { registerGetRolePowerShell } from "./register-get-role.js";
import { registerGetRoleMemberPowerShell } from "./register-get-role-member.js";
import { registerAddRoleMemberPowerShell } from "./register-add-role-member.js";
import { registerRemoveRoleMemberPowerShell } from "./register-remove-rolemember.js";
import { registerLockItemPowerShell } from "./register-lock-item.js";
import { registerUnlockItemPowerShell } from "./register-unlock-item.js";
import { registerProtectItemPowerShell } from "./register-protect-item.js";
import { registerUnprotectItemPowerShell } from "./register-unprotect-item.js";
import { registerNewRolePowerShell } from "./register-new-role.js";
import { registerRemoveRolePowerShell } from "./register-remove-role.js";
import { registerNewDomainPowerShell } from "./register-new-domain.js";
import { registerRemoveDomainPowerShell } from "./register-remove-domain.js";
import { registerTestAccountPowerShell } from "./register-test-account.js";

export function registerSecurityPowerShell(server: McpServer, config: Config) {
    registerGetUserPowerShell(server, config);
    registerNewUserPowerShell(server, config);
    registerRemoveUserPowerShell(server, config);
    registerDisableUserPowerShell(server, config);
    registerEnableUserPowerShell(server, config);
    registerUnlockUserPowerShell(server, config);
    registerSetUserPowerShell(server, config);
    registerGetDomainPowerShell(server, config);
    registerGetRolePowerShell(server, config);
    registerGetRoleMemberPowerShell(server, config);
    registerAddRoleMemberPowerShell(server, config);
    registerRemoveRoleMemberPowerShell(server, config);
    registerLockItemPowerShell(server, config);
    registerUnlockItemPowerShell(server, config);
    registerProtectItemPowerShell(server, config);
    registerUnprotectItemPowerShell(server, config);
    registerNewRolePowerShell(server, config);
    registerRemoveRolePowerShell(server, config);
    registerNewDomainPowerShell(server, config);
    registerRemoveDomainPowerShell(server, config);
    registerTestAccountPowerShell(server, config);
}